### ISSUE TITLE
Discussion about tests

### ISSUE THREAD

**Issue by halcaponey** [sadick254/scoped-style#11]
Hi
As the title says I'd like to discuss about tests.
I thought about it and I think this library needs 2 types of tests : 
 * unit tests : to do that we'll need to refactor the code into multiple functions who take the parsed template literal as an input and give an array of rules (as strings) as output, we could then test the resulting arrays against our expectation, we'll need a unit test library, my preference goes to [ava](https://github.com/avajs/ava) but in the end @sadick254 should choose
* end to end tests : since React, Preact, Hyperapp, and Infernojs are supported we'll need 4 apps (maybe a todo list app) one for each framework, then run the same end to end tests on all 4 of them to check if the css is well applied, we'll need a end to end test library, my preference goes to [cypress](https://github.com/cypress-io/cypress) but in the end @sadick254 should choose

What are your thought on this ?

**Comment by halcaponey** [comment]
I started working on [unit tests](https://github.com/halcaponey/scoped-css/tree/tests)

**Comment by sadick254** [comment]
Never used [ava](https://github.com/avajs/ava) before but it looks okay.

**Comment by sadick254** [comment]
@halcaponey Do we really need End to end testing with example apps? I don't think so, since we are only setting a `class` prop on the element to be styled.

**Comment by halcaponey** [comment]
Yeah, your right e2e is probably overkill
