### ISSUE TITLE
Problems with Comments, Animations and Referring

### ISSUE THREAD

**Issue by elbotho** [sadick254/scoped-style#14]
Love the idea of having CSS-in-JS in this tiny package!

I ran into some problems. Maybe I did it wrong, maybe it's not intended to work, but some info of what is supported would be nice (docs).

- Comments `/* using this syntax */ ` broke everything 
- I did not find a way to get Keyframe animations working
- I did not find a way to refer other Components ( like [this](https://www.styled-components.com/docs/advanced#referring-to-other-components))
- `::-webkit-slider-thumb` did not work

**Comment by tamb** [comment]
I think a way around the keyframes issue is this:
```js

const SPIN = 'spin';

styled.global`
 @keyframes ${SPIN}{
    from{
     transform: rotate(0deg);
    }
    to{
     transform: rotate(360deg);
    }
  }
`

styled('div')`
  animation: ${SPIN} 2s linear infinite
`
```

**Comment by tamb** [comment]
@sadick254  I think we should be able to forego css comments and focus more on adding support for keyframes and also improving the docs.  Now sure how you would use media queries and such.  Support for js variables? What's the scope of the enhancements here?  Do we want to support selecting nested components?

**Comment by halcaponey** [comment]
OK, so
* Comments works for me, can you provide a repro ?
* Keyframe animations, will PR soon
* Refering other Components is not supported, it sounds like a nightmare to implement, but you can still `:hover > svg { fill: rebeccapurple; }`, well not really, testing this I discovered that chainning pseudo selectors doesn't work, will PR soon
* dashes are not supported in pseudo selectors, will PR soon
