### ISSUE TITLE
Optimization, SSR, Checkbox styling, Pseudo selector functions, Special characters in content property

### ISSUE THREAD

**Issue by halcaponey** [sadick254/scoped-style#21]
Optimization : I noticed that on dom update, all app classes are updated. I'm going to research a solution for that.

SSR : There is no way to do SSR for now. I'm thinking maybe a callback as a second argument to the `scoped` function who default to `sheet.insertRule` (should resolve #5).

Checkbox styling : I didn't find a way to style checkboxes or radio buttons, all examples I found used the `+` or `~` combinators ([example](https://www.w3schools.com/howto/howto_css_custom_checkbox.asp)). Thinking about it we don't support :
* [Adjacent sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator)
* [General sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_combinator)
* [Descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator)

We only support :
* [Child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator)

And for selectors we don't support :
* [Class selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors)
* [ID selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/ID_selectors)
* [Attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)

We do support :
* [Type selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Type_selectors)
* [Universal selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Universal_selectors)

I'd like to add support to the missing ones, but the [Descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator) can start with `[a-z]` and I didn't found a regex that work for that. Personnaly I think we can allow ourselves to not support it, a distant child can always be styled with the `styled` function.

Pseudo selector functions : like [:nth-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child), are not supported. I'll add support.

Special characters in content property : like `content: "◀";`, I didn't found a way to regex special characters, I found a way to convert it with [http://enc.joyho.net/](http://enc.joyho.net/) but the result (`content: "\\25C0";`) doesn't work because backslashes are not supported. A simple change to the regex should fix that.

I already started working on these changes.

But I'll remain open to discussion about them.

**Comment by sadick254** [comment]
@halcaponey you have really done a good job in outlining what is currently supported and what is not. IMO we should prfioritize the SSR work and Optimisation. Those two will have a great impact on `scoped-style`. I have also been thinking about `classnames` being updated on `DOM` updates. I will put in some time this week to work on that. Thanks for all the PR's 👍

**Comment by halcaponey** [comment]
@sadick254 actually I already got all I listed done, I just need to add more unit test and update the doc.

**Comment by sadick254** [comment]
Thats good news. 
![](https://media.giphy.com/media/xHMIDAy1qkzNS/giphy.gif)

**Comment by halcaponey** [comment]
@sadick254 ok, pushed to master, could you check the readme ? I'm not a native english speaker.
