### ISSUE TITLE
Add support for different generateID strategies, change behaviour in test environment

### ISSUE THREAD

**Issue by kolodziejczakM** [sadick254/scoped-style#23]
Hello :)
Would be great to have possibility to edit generate id strategy or just to can change the way it works in test environment. 

Currently this library is generating new class names every time components are rendered. 
It's OK for development / production environments but it makes testing harder - e.g. snapshots fail on every test run, because of new classNames, see:

![image](https://user-images.githubusercontent.com/16230707/66721491-3bad3e00-ee04-11e9-9591-4cd041f4216f.png)

Which is making snapshots testing useless. Can we change that?

**Comment by sadick254** [comment]
Hey 😀, Thanks for opening this issue and raising a PR.
